version: "3.9"
services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - database
      - api
    volumes:
      - ./src/frontend:/app
    command: npm run dev
  api:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./src/backend:/app
    command: npm run start
  database:
    image: postgres:15.3
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
volumes:
  db-data: